Repository Jules-maker/client, pull requests merged in 2023-10, with the labels that each got.

#2 0.0.1
  package-lock.json
  package.json
  src/lib/auth.js
  src/routes/Register/+page.svelte
Labels: bug

#5 Math
  .gitignore
  .idea/.gitignore
  .idea/client.iml
  .idea/jsLibraryMappings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  package-lock.json
  package.json
  src/lib/components/header.svelte
  src/lib/components/home/checkImg.svelte
  src/lib/components/profile/login.svelte
  src/lib/components/profile/register.svelte
  src/routes/+page.svelte
  src/routes/HeaderNav/+page.svelte
  src/routes/Login/+page.svelte
  src/routes/Register/+page.svelte
  src/routes/Tester/+page.svelte
  src/routes/profile/+page.svelte
  src/routes/test/+page.svelte
  static/images/memes-test/SteamSetup.exe
  static/images/memes-test/dogo.jpg
  static/images/memes-test/finger.gif
  static/images/memes-test/grogu.gif
  static/images/memes-test/poupou.jpg
Labels: feat

#6 0.1.1
  -H
  package-lock.json
  package.json
  src/app.postcss
  src/lib/auth.js
  src/lib/components/header.svelte
  src/routes/Contact/+page.server.js
  src/routes/Contact/+page.svelte
Labels: feat

#7 0.3.0
  .idea/client.iml
  .idea/jsLibraryMappings.xml
  .idea/misc.xml
  package-lock.json
  package.json
  src/lib/components/header.svelte
  src/lib/components/home/checkImg.svelte
  src/lib/components/imagesGallery/imagesGallery.svelte
  src/routes/+page.svelte
  src/routes/imageUpload/+page.svelte
  src/routes/imagesGallery/+page.svelte
  src/routes/profile/+page.svelte
Labels: feat

#9 Jules
  package-lock.json
  package.json
  src/lib/components/header.scss
  src/lib/components/header.svelte
Labels: feat, style
